name: Generate PHPDoc

on:
  push:
    branches:
      - main  # adjust this branch name as needed
      - addPHPDocs

jobs:
  phpdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: composer update && composer install --no-interaction --prefer-dist

      - name: Generate PHPDoc
        run: vendor/bin/phpdoc -d src/ -t docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs