name: Generate and Publish Documentation

on:
  push:
    branches:
      - main  # Change to your default branch
      - addPHPDocs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.1, 8.0, 7.4 ]
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install phpDocumentor
        run: composer install

      - name: Generate Documentation
        run: vendor/bin/phpdoc -d ./src -t docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
